[ClassVersion("1.1.0.0"), FriendlyName("xRDSessionDeployment")]
class MSFT_xRDSessionDeployment : OMI_BaseResource
{
    [key, Description("Specifies the FQDN of a server to host the RD Connection Broker role service.")] string ConnectionBroker;
    [write, Description("Specifies the FQDN of a server to host the RD Web Access role service. ")] string WebAccessServer;
    [write, Description("Specifies the FQDN of a server to host the RD Session Host role service. ")] string SessionHosts[];
    [read, Description("Returns the licensing servers in a deployment. ")] string LicenseServers[];
};
